// Package protogeo is a library for encoding and decoding geobuf into Go structs using
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.10.1
// source: geobuf.proto
package protogeo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data_Geometry_Type int32

const (
	Data_Geometry_POINT              Data_Geometry_Type = 0
	Data_Geometry_MULTIPOINT         Data_Geometry_Type = 1
	Data_Geometry_LINESTRING         Data_Geometry_Type = 2
	Data_Geometry_MULTILINESTRING    Data_Geometry_Type = 3
	Data_Geometry_POLYGON            Data_Geometry_Type = 4
	Data_Geometry_MULTIPOLYGON       Data_Geometry_Type = 5
	Data_Geometry_GEOMETRYCOLLECTION Data_Geometry_Type = 6
)

// Enum value maps for Data_Geometry_Type.
var (
	Data_Geometry_Type_name = map[int32]string{
		0: "POINT",
		1: "MULTIPOINT",
		2: "LINESTRING",
		3: "MULTILINESTRING",
		4: "POLYGON",
		5: "MULTIPOLYGON",
		6: "GEOMETRYCOLLECTION",
	}
	Data_Geometry_Type_value = map[string]int32{
		"POINT":              0,
		"MULTIPOINT":         1,
		"LINESTRING":         2,
		"MULTILINESTRING":    3,
		"POLYGON":            4,
		"MULTIPOLYGON":       5,
		"GEOMETRYCOLLECTION": 6,
	}
)

func (x Data_Geometry_Type) Enum() *Data_Geometry_Type {
	p := new(Data_Geometry_Type)
	*p = x
	return p
}

func (x Data_Geometry_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_Geometry_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_geobuf_proto_enumTypes[0].Descriptor()
}

func (Data_Geometry_Type) Type() protoreflect.EnumType {
	return &file_geobuf_proto_enumTypes[0]
}

func (x Data_Geometry_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_Geometry_Type.Descriptor instead.
func (Data_Geometry_Type) EnumDescriptor() ([]byte, []int) {
	return file_geobuf_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys       []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`              // global arrays of unique keys
	Dimensions uint32   `protobuf:"varint,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"` // max coordinate dimensions, default 2
	Precision  uint32   `protobuf:"varint,3,opt,name=precision,proto3" json:"precision,omitempty"`   // number of digits after decimal point for coordinates, default 6
	// Types that are assignable to DataType:
	//	*Data_FeatureCollection_
	//	*Data_Feature_
	//	*Data_Geometry_
	DataType isData_DataType `protobuf_oneof:"data_type"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_geobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_geobuf_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Data) GetDimensions() uint32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *Data) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (m *Data) GetDataType() isData_DataType {
	if m != nil {
		return m.DataType
	}
	return nil
}

func (x *Data) GetFeatureCollection() *Data_FeatureCollection {
	if x, ok := x.GetDataType().(*Data_FeatureCollection_); ok {
		return x.FeatureCollection
	}
	return nil
}

func (x *Data) GetFeature() *Data_Feature {
	if x, ok := x.GetDataType().(*Data_Feature_); ok {
		return x.Feature
	}
	return nil
}

func (x *Data) GetGeometry() *Data_Geometry {
	if x, ok := x.GetDataType().(*Data_Geometry_); ok {
		return x.Geometry
	}
	return nil
}

type isData_DataType interface {
	isData_DataType()
}

type Data_FeatureCollection_ struct {
	FeatureCollection *Data_FeatureCollection `protobuf:"bytes,4,opt,name=feature_collection,json=featureCollection,proto3,oneof"`
}

type Data_Feature_ struct {
	Feature *Data_Feature `protobuf:"bytes,5,opt,name=feature,proto3,oneof"`
}

type Data_Geometry_ struct {
	Geometry *Data_Geometry `protobuf:"bytes,6,opt,name=geometry,proto3,oneof"`
}

func (*Data_FeatureCollection_) isData_DataType() {}

func (*Data_Feature_) isData_DataType() {}

func (*Data_Geometry_) isData_DataType() {}

type Data_Feature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Geometry *Data_Geometry `protobuf:"bytes,1,opt,name=geometry,proto3" json:"geometry,omitempty"`
	// Types that are assignable to IdType:
	//	*Data_Feature_Id
	//	*Data_Feature_IntId
	IdType           isData_Feature_IdType `protobuf_oneof:"id_type"`
	Values           []*Data_Value         `protobuf:"bytes,13,rep,name=values,proto3" json:"values,omitempty"`                                                     // unique values
	Properties       []uint32              `protobuf:"varint,14,rep,packed,name=properties,proto3" json:"properties,omitempty"`                                     // pairs of key/value indexes
	CustomProperties []uint32              `protobuf:"varint,15,rep,packed,name=custom_properties,json=customProperties,proto3" json:"custom_properties,omitempty"` // arbitrary properties
}

func (x *Data_Feature) Reset() {
	*x = Data_Feature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Feature) ProtoMessage() {}

func (x *Data_Feature) ProtoReflect() protoreflect.Message {
	mi := &file_geobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Feature.ProtoReflect.Descriptor instead.
func (*Data_Feature) Descriptor() ([]byte, []int) {
	return file_geobuf_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Data_Feature) GetGeometry() *Data_Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (m *Data_Feature) GetIdType() isData_Feature_IdType {
	if m != nil {
		return m.IdType
	}
	return nil
}

func (x *Data_Feature) GetId() string {
	if x, ok := x.GetIdType().(*Data_Feature_Id); ok {
		return x.Id
	}
	return ""
}

func (x *Data_Feature) GetIntId() int64 {
	if x, ok := x.GetIdType().(*Data_Feature_IntId); ok {
		return x.IntId
	}
	return 0
}

func (x *Data_Feature) GetValues() []*Data_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Data_Feature) GetProperties() []uint32 {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Data_Feature) GetCustomProperties() []uint32 {
	if x != nil {
		return x.CustomProperties
	}
	return nil
}

type isData_Feature_IdType interface {
	isData_Feature_IdType()
}

type Data_Feature_Id struct {
	Id string `protobuf:"bytes,11,opt,name=id,proto3,oneof"`
}

type Data_Feature_IntId struct {
	IntId int64 `protobuf:"zigzag64,12,opt,name=int_id,json=intId,proto3,oneof"`
}

func (*Data_Feature_Id) isData_Feature_IdType() {}

func (*Data_Feature_IntId) isData_Feature_IdType() {}

type Data_Geometry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             Data_Geometry_Type `protobuf:"varint,1,opt,name=type,proto3,enum=geobuf.Data_Geometry_Type" json:"type,omitempty"`
	Lengths          []uint32           `protobuf:"varint,2,rep,packed,name=lengths,proto3" json:"lengths,omitempty"` // coordinate structure in lengths
	Coords           []int64            `protobuf:"zigzag64,3,rep,packed,name=coords,proto3" json:"coords,omitempty"` // delta-encoded integer values
	Geometries       []*Data_Geometry   `protobuf:"bytes,4,rep,name=geometries,proto3" json:"geometries,omitempty"`
	Values           []*Data_Value      `protobuf:"bytes,13,rep,name=values,proto3" json:"values,omitempty"`
	CustomProperties []uint32           `protobuf:"varint,15,rep,packed,name=custom_properties,json=customProperties,proto3" json:"custom_properties,omitempty"`
}

func (x *Data_Geometry) Reset() {
	*x = Data_Geometry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Geometry) ProtoMessage() {}

func (x *Data_Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_geobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Geometry.ProtoReflect.Descriptor instead.
func (*Data_Geometry) Descriptor() ([]byte, []int) {
	return file_geobuf_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Data_Geometry) GetType() Data_Geometry_Type {
	if x != nil {
		return x.Type
	}
	return Data_Geometry_POINT
}

func (x *Data_Geometry) GetLengths() []uint32 {
	if x != nil {
		return x.Lengths
	}
	return nil
}

func (x *Data_Geometry) GetCoords() []int64 {
	if x != nil {
		return x.Coords
	}
	return nil
}

func (x *Data_Geometry) GetGeometries() []*Data_Geometry {
	if x != nil {
		return x.Geometries
	}
	return nil
}

func (x *Data_Geometry) GetValues() []*Data_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Data_Geometry) GetCustomProperties() []uint32 {
	if x != nil {
		return x.CustomProperties
	}
	return nil
}

type Data_FeatureCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features         []*Data_Feature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	Values           []*Data_Value   `protobuf:"bytes,13,rep,name=values,proto3" json:"values,omitempty"`
	CustomProperties []uint32        `protobuf:"varint,15,rep,packed,name=custom_properties,json=customProperties,proto3" json:"custom_properties,omitempty"`
}

func (x *Data_FeatureCollection) Reset() {
	*x = Data_FeatureCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_FeatureCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_FeatureCollection) ProtoMessage() {}

func (x *Data_FeatureCollection) ProtoReflect() protoreflect.Message {
	mi := &file_geobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_FeatureCollection.ProtoReflect.Descriptor instead.
func (*Data_FeatureCollection) Descriptor() ([]byte, []int) {
	return file_geobuf_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Data_FeatureCollection) GetFeatures() []*Data_Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Data_FeatureCollection) GetValues() []*Data_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Data_FeatureCollection) GetCustomProperties() []uint32 {
	if x != nil {
		return x.CustomProperties
	}
	return nil
}

type Data_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ValueType:
	//	*Data_Value_StringValue
	//	*Data_Value_DoubleValue
	//	*Data_Value_PosIntValue
	//	*Data_Value_NegIntValue
	//	*Data_Value_BoolValue
	//	*Data_Value_JsonValue
	ValueType isData_Value_ValueType `protobuf_oneof:"value_type"`
}

func (x *Data_Value) Reset() {
	*x = Data_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geobuf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Value) ProtoMessage() {}

func (x *Data_Value) ProtoReflect() protoreflect.Message {
	mi := &file_geobuf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Value.ProtoReflect.Descriptor instead.
func (*Data_Value) Descriptor() ([]byte, []int) {
	return file_geobuf_proto_rawDescGZIP(), []int{0, 3}
}

func (m *Data_Value) GetValueType() isData_Value_ValueType {
	if m != nil {
		return m.ValueType
	}
	return nil
}

func (x *Data_Value) GetStringValue() string {
	if x, ok := x.GetValueType().(*Data_Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Data_Value) GetDoubleValue() float64 {
	if x, ok := x.GetValueType().(*Data_Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *Data_Value) GetPosIntValue() uint64 {
	if x, ok := x.GetValueType().(*Data_Value_PosIntValue); ok {
		return x.PosIntValue
	}
	return 0
}

func (x *Data_Value) GetNegIntValue() uint64 {
	if x, ok := x.GetValueType().(*Data_Value_NegIntValue); ok {
		return x.NegIntValue
	}
	return 0
}

func (x *Data_Value) GetBoolValue() bool {
	if x, ok := x.GetValueType().(*Data_Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *Data_Value) GetJsonValue() string {
	if x, ok := x.GetValueType().(*Data_Value_JsonValue); ok {
		return x.JsonValue
	}
	return ""
}

type isData_Value_ValueType interface {
	isData_Value_ValueType()
}

type Data_Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Data_Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Data_Value_PosIntValue struct {
	PosIntValue uint64 `protobuf:"varint,3,opt,name=pos_int_value,json=posIntValue,proto3,oneof"`
}

type Data_Value_NegIntValue struct {
	NegIntValue uint64 `protobuf:"varint,4,opt,name=neg_int_value,json=negIntValue,proto3,oneof"`
}

type Data_Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Data_Value_JsonValue struct {
	JsonValue string `protobuf:"bytes,6,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

func (*Data_Value_StringValue) isData_Value_ValueType() {}

func (*Data_Value_DoubleValue) isData_Value_ValueType() {}

func (*Data_Value_PosIntValue) isData_Value_ValueType() {}

func (*Data_Value_NegIntValue) isData_Value_ValueType() {}

func (*Data_Value_BoolValue) isData_Value_ValueType() {}

func (*Data_Value_JsonValue) isData_Value_ValueType() {}

var File_geobuf_proto protoreflect.FileDescriptor

var file_geobuf_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x9a, 0x0a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x4f, 0x0a, 0x12, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x11, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52,
	0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x1a, 0xeb, 0x01, 0x0a, 0x07, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x06, 0x69, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0d, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x0e, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12,
	0x2b, 0x0a, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x42, 0x09, 0x0a, 0x07,
	0x69, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xfb, 0x02, 0x0a, 0x08, 0x47, 0x65, 0x6f, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x12, 0x52, 0x06,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x52, 0x0a, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x2a, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x0f,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x7d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x55, 0x4c,
	0x54, 0x49, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x49, 0x4e,
	0x45, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x55, 0x4c,
	0x54, 0x49, 0x4c, 0x49, 0x4e, 0x45, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x50, 0x4f, 0x4c, 0x59, 0x47, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4d,
	0x55, 0x4c, 0x54, 0x49, 0x50, 0x4f, 0x4c, 0x59, 0x47, 0x4f, 0x4e, 0x10, 0x05, 0x12, 0x16, 0x0a,
	0x12, 0x47, 0x45, 0x4f, 0x4d, 0x45, 0x54, 0x52, 0x59, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x06, 0x1a, 0x9e, 0x01, 0x0a, 0x11, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x08, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x2a, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x65, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x0f,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0xed, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6f,
	0x73, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x6f, 0x73, 0x49, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x65, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x65, 0x67, 0x49, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6a,
	0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geobuf_proto_rawDescOnce sync.Once
	file_geobuf_proto_rawDescData = file_geobuf_proto_rawDesc
)

func file_geobuf_proto_rawDescGZIP() []byte {
	file_geobuf_proto_rawDescOnce.Do(func() {
		file_geobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_geobuf_proto_rawDescData)
	})
	return file_geobuf_proto_rawDescData
}

var file_geobuf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_geobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_geobuf_proto_goTypes = []interface{}{
	(Data_Geometry_Type)(0),        // 0: geobuf.Data.Geometry.Type
	(*Data)(nil),                   // 1: geobuf.Data
	(*Data_Feature)(nil),           // 2: geobuf.Data.Feature
	(*Data_Geometry)(nil),          // 3: geobuf.Data.Geometry
	(*Data_FeatureCollection)(nil), // 4: geobuf.Data.FeatureCollection
	(*Data_Value)(nil),             // 5: geobuf.Data.Value
}
var file_geobuf_proto_depIdxs = []int32{
	4,  // 0: geobuf.Data.feature_collection:type_name -> geobuf.Data.FeatureCollection
	2,  // 1: geobuf.Data.feature:type_name -> geobuf.Data.Feature
	3,  // 2: geobuf.Data.geometry:type_name -> geobuf.Data.Geometry
	3,  // 3: geobuf.Data.Feature.geometry:type_name -> geobuf.Data.Geometry
	5,  // 4: geobuf.Data.Feature.values:type_name -> geobuf.Data.Value
	0,  // 5: geobuf.Data.Geometry.type:type_name -> geobuf.Data.Geometry.Type
	3,  // 6: geobuf.Data.Geometry.geometries:type_name -> geobuf.Data.Geometry
	5,  // 7: geobuf.Data.Geometry.values:type_name -> geobuf.Data.Value
	2,  // 8: geobuf.Data.FeatureCollection.features:type_name -> geobuf.Data.Feature
	5,  // 9: geobuf.Data.FeatureCollection.values:type_name -> geobuf.Data.Value
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_geobuf_proto_init() }
func file_geobuf_proto_init() {
	if File_geobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_geobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Feature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Geometry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_FeatureCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geobuf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_geobuf_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Data_FeatureCollection_)(nil),
		(*Data_Feature_)(nil),
		(*Data_Geometry_)(nil),
	}
	file_geobuf_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Data_Feature_Id)(nil),
		(*Data_Feature_IntId)(nil),
	}
	file_geobuf_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Data_Value_StringValue)(nil),
		(*Data_Value_DoubleValue)(nil),
		(*Data_Value_PosIntValue)(nil),
		(*Data_Value_NegIntValue)(nil),
		(*Data_Value_BoolValue)(nil),
		(*Data_Value_JsonValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geobuf_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geobuf_proto_goTypes,
		DependencyIndexes: file_geobuf_proto_depIdxs,
		EnumInfos:         file_geobuf_proto_enumTypes,
		MessageInfos:      file_geobuf_proto_msgTypes,
	}.Build()
	File_geobuf_proto = out.File
	file_geobuf_proto_rawDesc = nil
	file_geobuf_proto_goTypes = nil
	file_geobuf_proto_depIdxs = nil
}
